export const MOROCCO_CITIES: string[] = ["Béni Mellal-Khénifra",               
"Casablanca-Settat",                   
"Dakhla-Oued Ed-Dahab",                
"Drâa-Tafilalet",                      
"Fès-Meknès",                          
"Guelmim-Oued Noun",                   
"L'Oriental",                          
"Laâyoune-Sakia El Hamra",             
"Marrakech-Safi",                     
"Rabat-Salé-Kénitra",
"Souss-Massa",
"Tanger-Tétouan-Al Hoceïma",
];